### ISSUE TITLE
Fix Light/Dark toggle button

### ISSUE THREAD

**Issue by Vijaykv5** [neetozone/neeto-editor#1076]
The `toggle` button is not working as expected in the _[neeto-editor docs](https://neeto-editor.neeto.com/?path=/docs/welcome--docs)_

- The toggle is working on some pages and components but while taking as a whole, it's not updating the states.

<img width="1073" alt="Screenshot 2024-04-24 at 11 27 19 PM" src="https://github.com/bigbinary/neeto-editor/assets/94985341/bde1c1ef-7445-45b0-81c0-6d1e2fe2a51d">

**Comment by AbhayVAshokan** [comment]
Thank you for reporting the issue. I shall get this fixed.

UI _t small _t
@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
I understand the confusion here. The theme icon does not control the global theme of the storybook as a whole. We use the theme to switch to the dark theme for the Editor component. 

Take a look at the [Image Upload documentation](https://neeto-editor.neeto.com/?path=/docs/examples-customize-options-image-upload--docs):

![Apr-25-2024 18-29-10](https://github.com/bigbinary/neeto-editor/assets/35297280/a45005e5-152f-458a-8445-82c53e5d457a)

By default [neetoUI color palette](https://neeto-ui.neeto.com/?path=/docs/foundation-colors--docs) comes with two themes: dark and light. We showcase how neetoEditor looks in the two themes with the theme configuration of storybook.

Closing the issue since there are no further action items. Please do let me know if anything else needs to be clarified.

**Comment by Vijaykv5** [comment]
@AbhayVAshokan Cool! 
Sorry for the Misunderstanding
