### ISSUE TITLE
Not able to remove the bullet point number

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1103]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/6211

https://bigbinary.neetorecord.com/watch/0e64e1ff-916c-4ad0-ae99-6869888254d6

- Please try reproducing the issue and compare it with the default behaviour of WYSIWYG editors.

**Comment by deepakjosp** [comment]
@AbhayVAshokan I was not able to reproduce this with the content that I typed in the editor. It might be because of the styles that was added from the place where this content is copied. A paste and match style might not have introduced it I guess. Please let me know your thoughts.

https://deepak-jose.neetorecord.com/recordings/93a5f326-530f-4956-9a22-b0ad03d9b31c

**Comment by AbhayVAshokan** [comment]
I am unable to reproduce this issue too. It could be the rich text styles of pasted content.
