### ISSUE TITLE
Implement responsive Menu using three dot menu approach

### ISSUE THREAD

**Issue by praveen-murali-ind** [neetozone/neeto-editor#1112]
@deepakjosp _a As discussed, please start working on this once https://github.com/bigbinary/neeto-editor/pull/1111 is merged.

cc @AbhayVAshokan 

Ref - https://github.com/bigbinary/neeto-editor/issues/1100#issuecomment-2133641974

GitHub Ref

https://github.com/bigbinary/neeto-editor/assets/48869249/c8fe076f-777f-4f22-b9ec-fe292c00bbdd

**Comment by deepakjosp** [comment]
@AbhayVAshokan the estimate for this went beyond the plan because:
1. I had to entirely refactor the way the fixed menu was rendered.
2. Few of the helpers and component which were used in fixed menu was re-used by bubble menu. I had to fix those because I made changes to the utils and bubble menu was not compatible.

Updating the ETA to 1.75D _t
