### ISSUE TITLE
Updated content not displayed, but value is present in the editor. 

### ISSUE THREAD

**Issue by vysakh-poulose** [neetozone/neeto-editor#146]
If we pass a state value, that updates on a certain action, as initialValue to the editor. The updated value is not displayed, but it's value is present in the editor. So, submission of editor is successful.

https://www.loom.com/share/0664d05dedfa4dbabcdb1b61aa7f8849

**Comment by AbhayVAshokan** [comment]
@amaldinesh7 please have a look at this issue. 

- [ ] We need to insert content into the editor using an external trigger (dropdown).

This [codesandbox](https://codesandbox.io/s/neeto-desk-insert-content-using-external-trigger-t7r4x) is a concise representation of the issue (button instead of a dropdown). It is possible to solve the issue by uncommenting `line 14`. Should we add a new prop that does the same or would this implementation suffice?

- [ ] Also, please note, the below issue mentions the requirement of custom slash commands.

Ref: https://github.com/bigbinary/neeto-desk-web/issues/11838
