### ISSUE TITLE
Unable to add images using URL

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#312]
Refer: https://github.com/bigbinary/neeto-planner-web/issues/2041

**Comment by AbhayVAshokan** [comment]
@sachingiri29 please have a look:
https://vimeo.com/738501592/3924a2f3ba

**Comment by sachingiri29** [comment]
@AbhayVAshokan I got the point. But one thing, me as a user, I went to click on the Share button and then copied the link right. That's a possibility for other users as well, isn't it? So, my point is how can we handle this scenario because there might be a point where the user wouldn't think about copying the image's address and clicking on the share button to get the link? 

I verified it as per your saying, and it's working fine I can say. And if this can't have any other alternatives then we can ahead with closing the issue.
Thanks.

**Comment by AbhayVAshokan** [comment]
I don't think it might be able to display the image from a general URL. Instead, we can think of a fallback when the image URL is invalid.

**Comment by sachingiri29** [comment]
> Instead, we can think of a fallback when the image URL is invalid.

This seems like a valid solution for now.

**Comment by sandip-mane** [comment]
Seems like a difficult problem to solve. But for now, I guess we can show an error when the URL does not yield an image.
@AbhayVAshokan can we do that?

**Comment by AbhayVAshokan** [comment]
@sandip-mane, yes. I have raised a PR for this: https://github.com/bigbinary/neeto-editor-tiptap/pull/314
