### ISSUE TITLE
Dark Reader extension interfering with editor

### ISSUE THREAD

**Issue by vysakh-m** [neetozone/neeto-editor#353]
Ref: https://github.com/bigbinary/neeto-quiz-web/issues/1358

<img width="1002" alt="Screenshot 2022-09-17 at 12 08 36 AM" src="https://user-images.githubusercontent.com/29486171/190709354-4478b773-aa99-47aa-9859-a7201168c903.png">

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
I have thoroughly looked into the issue and found that this is due to two of the official extensions from Tipttap: `TextStyle` and `Color`. I have raised an issue for the same at https://github.com/ueberdosis/tiptap/issues/3213. The proper fix for the same will take some time. Meanwhile, I'll discuss it with the neetoEditor team and try to come up with an alternative solution for the same.
cc: @vysakh-m, @chiraggshah 

**Update**: Removing the above-mentioned extensions till the proper solution is released.
