### ISSUE TITLE
Why only pic and not files

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#395]
https://www.loom.com/share/c909ca5da60a4426953ba6706086ed9d

**Comment by AbhayVAshokan** [comment]
@neerajdotname please share your thoughts https://vimeo.com/757839641/9d71246cbf

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan Thanks. Let me look into it.

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan @sandip-mane @chiraggshah @vysaghsekharbb @praveen-murali-ind @Tsudhishnair https://www.loom.com/share/0c63803938c04dc882a5a5bf98d8f27e

**Comment by AbhayVAshokan** [comment]
@neerajdotname regarding the menu contrast, it would fixed in the next compliance fix: https://github.com/bigbinary/neeto_commons/pull/567

After recent design UI updates, the editor UI looks like this
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/35297280/194477185-a435a8ea-5661-436d-afdc-761ba3d7232c.png">

**Comment by sandip-mane** [comment]
@neerajdotname https://app.usebubbles.com/8mWRo1EPUVZRU2nvE4o9yF/attachments-vs-editor

**Comment by vysaghsekharbb** [comment]
@neerajdotname Can we merge this ticket with '[Handling attachments #18](https://github.com/bigbinary/neeto-engineering-ui-ux/issues/18)'

**Comment by AbhayVAshokan** [comment]
I agree. Both these issues are similar.
