### ISSUE TITLE
Add workflow for production deployment to Vercel

### ISSUE THREAD

**Issue by KrishnapriyaSkk** [neetozone/neeto-editor#568]

**Comment by ghousemohamed** [comment]
@neerajdotname Please watch https://www.loom.com/share/8d61c626852d4441898fbc52b7eb4562

---

We need to keep this in mind when removing my account since it is associated with the deployment secret key for bigbinary website and neeto website. So we need to create vercel tokens in the common user which will be present in neeto team in vercel.
