### ISSUE TITLE
Unable to upload images to description

### ISSUE THREAD

**Issue by neenu-chacko** [neetozone/neeto-editor#584]
Please refer this video: https://app.usebubbles.com/wJLrjVhx2EzZwAtRpjB6XY/image-upload-bug

**Comment by mayanksharma4132** [comment]
@AbhayVAshokan _A
Event propagation needs to be handled in attachment modal.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I think this issue is related to the implementation of certain functionality in neetoPlanner.
<img width="706" alt="Screenshot 2023-01-30 at 5 08 21 PM" src="https://user-images.githubusercontent.com/70290286/215467421-8a56c101-5c7d-4e5d-a1aa-d19e139a3d7b.png">
as you can see in the above snippet when a mouse clicks outside the editor, the data gets saved and the editor is unmounted.

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a This issue is more complex than we expected, This issue cannot be solved only by removing the state change which unmounts the editor, I think the useOnClickOutside hook will have to be removed to solve this issue, I also tried stopping event propagation from editor but still this issue persists.

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's make the changes as we discussed over the call.

**Comment by gaagul** [comment]
> @gaagul _a let's make the changes as we discussed over the call.

@AbhayVAshokan I think we will have to remove the outside click event fully to make it work properly. I will try to change the feature such that only clicking the save button will unmount the editor and outside click will only make changes to content without unmounting the editor.

**Comment by AbhayVAshokan** [comment]
Yes, let's remove it.
