### ISSUE TITLE
Image caption not center aligned.

### ISSUE THREAD

**Issue by mohitharshan123** [neetozone/neeto-editor#742]
Image caption is not aligned in center on published page in production environment.

<img width="975" alt="Screenshot 2023-04-13 at 10 13 39 AM" src="https://user-images.githubusercontent.com/82232148/231656654-13ad2241-cd0d-4aec-a677-6f1f300b0927.png">

https://vimeo.com/817188054/05c50ddcbc
article link- https://chattest3.neetokb.com/admin/articles/sample-12345/edit

**Comment by mohitharshan123** [comment]
There is an anchor tag getting inserted under `figcaption`.

**Comment by AbhayVAshokan** [comment]
@gaagul _a
1. We had discussed the solution to the alignment issues for portrait images. Make sure the changes are made in the neetoKB's EUI side as well once rolled out.
2. The appearance of underline when hovering over the anchor tag is annoying please make necessary changes to the styles so that it doesn't appear.
3. Verify the spacing between image and caption once point 1 is solved.
