### ISSUE TITLE
Numbered list and bulleted list options are not working properly in neeto-chat

### ISSUE THREAD

**Issue by Prasannams97** [neetozone/neeto-editor#744]
https://www.loom.com/share/76e23f205b08453eb0dfb8563a0cf3b8

**Comment by Prasannams97** [comment]
bug _t

**Comment by Prasannams97** [comment]
caught-by-cypress _t

**Comment by AbhayVAshokan** [comment]
This is expected behavior of "Shift + Enter" in WYSIWYG editors. neetoChat has mapped the "Enter" key to sending the message. Hence, the only choice of creating a new line comes with "Shift + Enter".

"Enter" to send is a common pattern in most chat applications. So we shouldn't change it since it offers a good user experience.

@gaagul _a let's override the default behavior of "Shift + Enter" in neetoChat by modifying the `KeyboardShortcuts` extension within neetoChat.

**Comment by gaagul** [comment]
@akhil-gautam This specific issue can be solved, but once it's done, there may be other issues related to the editor writing flow that need to be addressed. Additionally, I noticed that in all other neeto products we use "CMD+Enter" to send messages, while neetoChat uses "Enter" which overwrites all the default behaviour of "Enter" key. I was wondering if it's possible to configure neetoChat to use the same shortcut as other products.

cc// @AbhayVAshokan

**Comment by akhil-gautam** [comment]
The reason neetoChat uses `enter` is that it is primarily a chat application. Always pressing `cmd+enter` would be frustrating for agents. @gaagul

**Comment by AbhayVAshokan** [comment]
In that case, I'll have a look at this problem this weekend. This has several interesting edge cases that need to be addressed. @gaagul you can also explore more on the approach we discussed and check if there is a proper solution to the issue.

**Comment by gaagul** [comment]
Extracted to https://github.com/bigbinary/neeto-chat-web/issues/7259
