### ISSUE TITLE
Ability to show only a few items so that the horizontal scrollbar doesn't come up

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#767]
https://www.loom.com/share/3a0dddf3ba90443b81b36a721edf36bf

feature _t

**Comment by AbhayVAshokan** [comment]
This is a good idea. Let's take this up @gaagul _a

**Comment by AbhayVAshokan** [comment]
To implement this feature, it is necessary that the link option and table option are moved to a Modal instead of a Dropdown. 

@VarunSriram99: can you please check if we have any Cypress tests for the link/table options of neetoEditor? 

@gaagul: Add an `isCollapsed` prop. It should be false by default. Show the Bold, Italics, Underline, and Strike options if it is enabled. The rest should be moved to the dropdown.

**Comment by gaagul** [comment]
> To implement this feature, it is necessary that the link option and table option are moved to a Modal instead of a Dropdown.

@AbhayVAshokan  We need consider "emoji" and "text-color" option as well, Moving "emoji-option" to a modal will make it difficult for the user to access it and with the text color option the changes might not be visible if it is moved into a modal.

**Comment by AbhayVAshokan** [comment]
@gaagul LMK your thoughts on this new UI: https://vimeo.com/831173174/bdd4d77623

cc: @neerajdotname

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan sounds good 👍

**Comment by VarunSriram99** [comment]
@AbhayVAshokan we have tests for links implemented in neetoDesk. An immediate example would be [this](https://github.com/bigbinary/neeto-desk-web/blob/f6fa34bfe3c9b2b11f27794a75756ba99e57305f/cypress-tests/cypress/e2e/tickets/verifyNewTicket.spec.js) spec.

**Comment by AbhayVAshokan** [comment]
Understood. This change in neetoEditor might affect these tests.
