### ISSUE TITLE
UX feedback 

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#833]
@AbhayVAshokan _a https://www.loom.com/share/ee9cd78d8c7b401d99e2af5d457f57ec

**Comment by gaagul** [comment]
@neerajdotname I will improve the UX of link extension in #835 , Most of the styles are overridden at neeto-kb side, we can update the styles once we finalize the new color values.

cc: @AbhayVAshokan

**Comment by neerajsingh0101** [comment]
@gaagul @sandip-mane @philson-philip  Do you know any particular reason why the styles are overridden?

**Comment by gaagul** [comment]
The reason might be because the neetoEditor has a default background of white even for the menu, but the editor in neetoKb takes up the entire screen and the white background might not make the menu stand up in the whole screen and a gray background is given.

**Comment by AbhayVAshokan** [comment]
@gaagul we shouldn't entirely blame neetoKB for this one. 

>  Do you know any particular reason why the styles are overridden?

These style changes are necessary since the UI requirements for neetoEditor in neetoKB are different from the use cases in other places. neetoKB requires a neetoEditor that spans the entire page and is used to write articles. The menu should stand out to the user. For the other requirements, neetoEditor is a replacement for a Textarea component. Hence, there are differences in the styles.

We should fix the active state of the menu so that it does stand out correctly. We'll coordinate with @philson-philip to get this fixed ASAP.

**Comment by gaagul** [comment]
> @gaagul we shouldn't entirely blame neetoKB for this one.

@AbhayVAshokan  Yes I understand, I had mentioned about the situation with neetoKB in the previous comment.

**Comment by philson-philip** [comment]
@AbhayVAshokan Earlier the active state and menubar background was the same shade of grey color. So that the active state was not at all visible and I thought it was a bug. After the discussion with the design team, we made the menubar background a lighter shade of grey to make the active state visible. We are overriding a few styles for `neetoKB` as per the article editor design. We need to improve the color palette to fix the contrast issues with the active state. 

@vysaghsekharbb _a Can you look into this issue and suggest a better color palette?

**Comment by vysaghsekharbb** [comment]
@philson-philip Let's have a quick call and fix the colors ?

**Comment by vysaghsekharbb** [comment]
@philson-philip 

Please find the updates below as our meeting

https://app.usebubbles.com/cXpB6DdiEMYdU7BqDLhQDH

Figma File
https://www.figma.com/file/Osl7GBbBk0iwVMc57366nZ/neetoKB?type=design&node-id=5704-29355&mode=design&t=2PLrSqTTSXDXmnXu-4

**Comment by philson-philip** [comment]
@vysaghsekharbb This looks good to me. 

@AbhayVAshokan In this design @vysaghsekharbb has categorised menubar icons. Can you look into that work in neetoEditor?

**Comment by AbhayVAshokan** [comment]
Yes, this looks good to me too.
@gaagul _a let's take this up.

**Comment by gaagul** [comment]
Closing this issue since all the changes to the Menu styles an LinkOption have been completed.
