### ISSUE TITLE
Add prop to disable opening images in a new tab

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#859]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/4574

- [ ] Add a `openImageInNewTab` prop (true by default). If it is falsy, the rendered images should not open in a new tab when clicked.
- [ ] Add a data migration in neetoKB to rollout this behaviour to all the images.

Refer: https://vimeo.com/853679057/ca6ab51d56
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan Since we are already in the works of running a migration to update the structure of images in neetoKb, I think it will be better if we update the existing migration to make this small change in styles instead of running a whole new data-migration, Please let me know your thoughts on this.

**Comment by AbhayVAshokan** [comment]
Agreed. Please add the necessary changes and mention the same as a comment
