### ISSUE TITLE
Editor content not updating in real time

### ISSUE THREAD

**Issue by vysakh-poulose** [neetozone/neeto-editor#980]
https://vimeo.com/898569734/1f639874b4?share=copy

cc @VarunSriram99

**Comment by AbhayVAshokan** [comment]
@vysakh-poulose, @VarunSriram99: We have a debounce on the `onChange` method in neetoEditor. neetoEditor was facing significant performance-related issues due to multiple unnecessary re-renders on pressing each character. After multiple failed attempts on memoizations, we added a debounce of 100ms to prevent these re-renders. The Cypress team had added a small delay on the Cypress side to handle this case. 

discussion _t

**Comment by VarunSriram99** [comment]
@AbhayVAshokan there are genuine cases where this debounce can cause issues. Consider an example where a user is updating the data in multiple records from a reference file. They might be copy pasting the data.

Since the editor is most likely the last field in the form, they might have the tendency to use the shortcut key to submit the form. So they might do `⌘+v` and `⌘+enter`. This can happen under that 100ms debounce which causes the form to be submitted without the updated data. This can cause a bad user experience and confusion among the users due to the change in the data.

If there's no way out of the debounce then we should at least think of a mechanism which prevents the user from submitting the stale data.

**Comment by AbhayVAshokan** [comment]
Understood. We will look more into the issue and let you know.

@gaagul _a spike _t

**Comment by vysakh-poulose** [comment]
@AbhayVAshokan Any updates on this?
cc @gaagul

**Comment by AbhayVAshokan** [comment]
@vysakh-poulose I did explore a few strategies but was unsuccessful. The performance is taking a hit. I need some more time to check memory leaks and associated optimizations.

**Comment by vysakh-poulose** [comment]
@AbhayVAshokan Any updates on this?
cc @gaagul

**Comment by AbhayVAshokan** [comment]
We couldn't take this up in the previous milestone. I shall take this up myself and share the updates here.

@AbhayVAshokan _a

**Comment by vysakh-poulose** [comment]
@AbhayVAshokan Any updates on this?

**Comment by AbhayVAshokan** [comment]
I'll fix this in M7.

**Comment by AbhayVAshokan** [comment]
Fixed by https://github.com/bigbinary/neeto-editor/pull/1066

https://abhay-ashokan.neetorecord.com/watch/d9f176fd-f1f5-44bf-b5d1-807487da0533
